// Code generated by hertz generator.

package lxyhttp

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebaiduhotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportexcelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importexcelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buzzwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbuzzwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removebuzzwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebuzzwordparaphraseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbuzzwordtagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removebuzzwordtagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buzzwordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryallbuzzwordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querybuzzwordsbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querybuzzwordsbytagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tag0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addtagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removetagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryalltagtypesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id_oneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _typeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetagoftypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _type0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addtagtypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removetagtypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryalltagsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytagsbytypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytagsbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}
