// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameTagType = "tag_types"

// TagType mapped from table <tag_types>
type TagType struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:ID" json:"id"`         // ID
	Value      string    `gorm:"column:value;not null;comment:标签类型名称" json:"value"` // 标签类型名称
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName TagType's table name
func (*TagType) TableName() string {
	return TableNameTagType
}
