// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameWord = "words"

// Word mapped from table <words>
type Word struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:ID" json:"id"`        // ID
	Value      string    `gorm:"column:value;not null;comment:流行语名称" json:"value"` // 流行语名称
	Paraphrase string    `gorm:"column:paraphrase;comment:释义" json:"paraphrase"`   // 释义
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	Tags       []Tag     `gorm:"many2many:word_tags" json:"tags"`
}

// TableName Word's table name
func (*Word) TableName() string {
	return TableNameWord
}
