// Code generated by hertz generator.

package lxyhttp

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	lxyhttp "github.com/yanguiyuan/lxy/biz/model/lxyhttp"
)

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req lxyhttp.LoginOrRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(lxyhttp.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}

// Logout .
// @router /logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	//var err error

	resp := new(lxyhttp.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req lxyhttp.LoginOrRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(lxyhttp.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}
